title: Homebrew Documentation
description: Documentation for the missing package manager for macOS (or Linux).
url: https://docs.brew.sh

remote_theme: Homebrew/brew.sh

exclude:
  - bin
  - CNAME
  - docs_rubocop_style.yml
  - Gemfile*
  - Rakefile
  - vale-styles
  - vendor

plugins:
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

permalink: :title

defaults:
  - scope:
      path: ""
    values:
      layout: default
      image: /assets/img/homebrew-256x256.png
      search_name: Documentation
      search_site: docs
  - scope:
      path: governance
    values:
      category: governance-archives

kramdown:
  toc_levels: 2..3

logo: /assets/img/homebrew.svg

twitter:
  username: MacHomebrew

facebook:
  publisher: https://www.facebook.com/machomebrew/
